import {Book} from '../types/book.model';

export const books: Book[] = [
  // Category 1
  { id: 1, categoryId: 1, title: 'The Midnight Library', author: 'Matt Haig', image: 'https://img.freepik.com/free-vector/flat-vertical-poster-template-world-book-day-celebration_23-2150201456.jpg?semt=ais_incoming&w=740&q=80', description: 'A novel about choices, regrets, and the infinite possibilities of life.', price: 14.99, productDetail: 'Hardcover, 304 pages, Publisher: Viking, Language: English', aboutAuthor: 'Matt Haig is a British author known for his novels and nonfiction works about mental health and human existence.' },
  { id: 2, categoryId: 1, title: 'Where the Crawdads Sing', author: 'Delia Owens', image: 'https://static.vecteezy.com/system/resources/thumbnails/003/533/144/small/book-launch-and-publishing-flyer-design-template-new-book-launch-announcement-poster-leaflet-template-a4-template-brochure-design-cover-flyer-poster-print-ready-free-vector.jpg', description: 'A coming-of-age story and murder mystery set in the marshes of North Carolina.', price: 12.99, productDetail: 'Paperback, 368 pages, Publisher: G.P. Putnam\'s Sons, Language: English', aboutAuthor: 'Delia Owens is an American author and zoologist known for her debut novel set in the natural world.' },
  { id: 3, categoryId: 1, title: 'The Vanishing Half', author: 'Brit Bennett', image: 'https://thumbs.dreamstime.com/b/vector-sketch-poster-old-rare-vintage-books-old-vintage-books-rare-literature-sketch-poster-library-bookshop-116130754.jpg', description: 'Explores the lives of twin sisters and themes of identity and race.', price: 16.5, productDetail: 'Hardcover, 352 pages, Publisher: Riverhead Books, Language: English', aboutAuthor: 'Brit Bennett is an American writer whose works often explore family, identity, and social issues.' },

  // Category 2
  { id: 4, categoryId: 2, title: 'Educated', author: 'Tara Westover', image: 'https://images-cdn.ubuy.co.id/634d04adeac9051d7668aadb-reading-can-seriously-damage-your.jpg', description: 'A memoir about growing up in a strict and abusive household and pursuing education.', price: 13.99, productDetail: 'Hardcover, 352 pages, Publisher: Random House, Language: English', aboutAuthor: 'Tara Westover is an American memoirist and historian who grew up in rural Idaho and self-educated herself.' },
  { id: 5, categoryId: 2, title: 'Becoming', author: 'Michelle Obama', image: 'https://m.media-amazon.com/images/I/81w+yOJbXeS.jpg', description: 'Memoir of the former First Lady sharing her journey from childhood to the White House.', price: 18.99, productDetail: 'Hardcover, 448 pages, Publisher: Crown, Language: English', aboutAuthor: 'Michelle Obama is an American attorney, author, and former First Lady of the United States.' },
  { id: 6, categoryId: 2, title: 'The Silent Patient', author: 'Alex Michaelides', image: 'https://m.media-amazon.com/images/I/71PPNDHGIiS._AC_UF894,1000_QL80_.jpg', description: 'A psychological thriller about a woman who stops speaking after a violent act.', price: 15.99, productDetail: 'Hardcover, 336 pages, Publisher: Celadon Books, Language: English', aboutAuthor: 'Alex Michaelides is a British-Cypriot author known for his gripping psychological thrillers.' },

  // Category 3
  { id: 7, categoryId: 3, title: 'Normal People', author: 'Sally Rooney', image: 'https://i0.wp.com/ebookfriendly.com/wp-content/uploads/2016/04/Vintage-book-posters-Book-Week-November-1930.jpg?resize=540%2C815&ssl=1', description: 'Explores the intricate relationship between two young adults in Ireland.', price: 14.5, productDetail: 'Paperback, 273 pages, Publisher: Faber & Faber, Language: English', aboutAuthor: 'Sally Rooney is an Irish author celebrated for her novels about love, friendship, and social dynamics.' },
  { id: 8, categoryId: 3, title: 'Little Fires Everywhere', author: 'Celeste Ng', image: 'https://images-platform.99static.com//eVPuht0_BGkyNmVOt9EMFSTe1YQ=/316x351:816x851/fit-in/500x500/99designs-contests-attachments/68/68113/attachment_68113009', description: 'A story about motherhood, secrets, and social class in a suburban town.', price: 16.99, productDetail: 'Paperback, 352 pages, Publisher: Penguin, Language: English', aboutAuthor: 'Celeste Ng is an American novelist known for her works exploring family dynamics and societal pressures.' },
  { id: 9, categoryId: 3, title: 'The Night Circus', author: 'Erin Morgenstern', image: 'https://c8.alamy.com/comp/2EKYXMP/vintage-books-fair-and-literature-festival-sketch-poster-vector-book-store-and-study-or-education-books-fair-antiquarian-poems-and-novels-ancient-p-2EKYXMP.jpg', description: 'A fantasy novel about a magical competition between two young illusionists.', price: 13.5, productDetail: 'Hardcover, 387 pages, Publisher: Doubleday, Language: English', aboutAuthor: 'Erin Morgenstern is an American author known for her imaginative and visually rich storytelling.' },

  // Category 4
  { id: 10, categoryId: 4, title: 'Circe', author: 'Madeline Miller', image: 'https://resources.eventgroove.com.au/images/template/7474/31/books-poster__front.jpg', description: 'A retelling of the story of the enchantress Circe from Greek mythology.', price: 17.99, productDetail: 'Hardcover, 400 pages, Publisher: Little, Brown and Company, Language: English', aboutAuthor: 'Madeline Miller is an American novelist and classicist who writes modern adaptations of Greek myths.' },
  { id: 11, categoryId: 4, title: 'The Book Thief', author: 'Markus Zusak', image: 'https://m.media-amazon.com/images/I/71xXd41rKDS._AC_SL1500_.jpg', description: 'A story set in Nazi Germany narrated by Death, about a young girl who loves books.', price: 12.99, productDetail: 'Paperback, 552 pages, Publisher: Knopf, Language: English', aboutAuthor: 'Markus Zusak is an Australian author known for his young adult and historical fiction.' },
  { id: 12, categoryId: 4, title: 'Sapiens: A Brief History of Humankind', author: 'Yuval Noah Harari', image: 'https://i.pinimg.com/564x/58/dc/26/58dc26d70ec2bd146bd7491351d714a9.jpg', description: 'Explores the history of humans from the Stone Age to the modern era.', price: 19.5, productDetail: 'Paperback, 498 pages, Publisher: Harper, Language: English', aboutAuthor: 'Yuval Noah Harari is an Israeli historian and professor known for his works on macrohistory.' },

  // Category 5
  { id: 13, categoryId: 5, title: 'The Alchemist', author: 'Paulo Coelho', image: 'https://img.freepik.com/free-vector/flat-vertical-poster-template-world-book-day-celebration_23-2150178584.jpg?semt=ais_hybrid&w=740&q=80', description: 'A philosophical story about following your dreams and listening to your heart.', price: 10.99, productDetail: 'Paperback, 208 pages, Publisher: HarperOne, Language: English', aboutAuthor: 'Paulo Coelho is a Brazilian author celebrated for his inspirational and spiritual novels.' },
  { id: 14, categoryId: 5, title: 'Atomic Habits', author: 'James Clear', image: 'https://s26162.pcdn.co/wp-content/uploads/2017/04/42179u-Edit_500_2048x2048.jpg', description: 'A practical guide to building good habits and breaking bad ones.', price: 18.5, productDetail: 'Hardcover, 320 pages, Publisher: Avery, Language: English', aboutAuthor: 'James Clear is an American author and speaker specializing in habits, decision-making, and continuous improvement.' },
  { id: 15, categoryId: 5, title: 'The Four Winds', author: 'Kristin Hannah', image: 'https://litlearnact.wordpress.com/wp-content/uploads/2014/09/photo-16.jpg', description: 'A historical novel about love, courage, and resilience during the Great Depression.', price: 16.0, productDetail: 'Hardcover, 464 pages, Publisher: St. Martin\'s Press, Language: English', aboutAuthor: 'Kristin Hannah is an American author known for her emotional and historical novels.' },

  // Category 6
  { id: 16, categoryId: 6, title: 'The Outsider', author: 'Stephen King', image: 'https://media.istockphoto.com/id/2163509266/vector/book-market.jpg?s=612x612&w=0&k=20&c=SaR99Y_5GwCJ1ZcNR3FWaMw3bEbZ70gKn6kOCB6yjm0=', description: 'A thrilling crime story with a supernatural twist.', price: 17.0, productDetail: 'Hardcover, 576 pages, Publisher: Scribner, Language: English', aboutAuthor: 'Stephen King is an American author renowned for his horror, supernatural fiction, suspense, and fantasy novels.' },
  { id: 17, categoryId: 6, title: 'Dune', author: 'Frank Herbert', image: 'https://m.media-amazon.com/images/I/51HUbQBMuRL._SL500_.jpg', description: 'Epic science fiction story about politics, religion, and survival on a desert planet.', price: 15.5, productDetail: 'Paperback, 688 pages, Publisher: Ace, Language: English', aboutAuthor: 'Frank Herbert was an American science-fiction author best known for the Dune saga.' },
  { id: 18, categoryId: 6, title: 'To Kill a Mockingbird', author: 'Harper Lee', image: 'https://img.lovepik.com//Templet_origin_pic/04/70/11/38e37416dd2e9117040a4c3bf871a4a8.jpg_detail.jpg!detail808', description: 'A classic novel about racial injustice and moral growth in the American South.', price: 13.0, productDetail: 'Paperback, 336 pages, Publisher: Harper Perennial Modern Classics, Language: English', aboutAuthor: 'Harper Lee was an American novelist widely known for her novel To Kill a Mockingbird.' },

  // Category 7
  { id: 19, categoryId: 7, title: 'Pachinko', author: 'Min Jin Lee', image: 'https://vintagraph.com/cdn/shop/products/11093u3_book_36-USE-ME-800.jpg?v=1619706424', description: 'A multi-generational saga about a Korean family living in Japan.', price: 14.5, productDetail: 'Hardcover, 496 pages, Publisher: Grand Central Publishing, Language: English', aboutAuthor: 'Min Jin Lee is a Korean-American author whose works explore identity, family, and history.' },
  { id: 20, categoryId: 7, title: 'The Hobbit', author: 'J.R.R. Tolkien', image: 'https://img.pikbest.com/templates/bg/20201026/bg/70aeef9dc0e00_429468.png!w700wp', description: 'A fantasy adventure about Bilbo Baggins and his journey with dwarves.', price: 12.5, productDetail: 'Paperback, 310 pages, Publisher: Houghton Mifflin Harcourt, Language: English', aboutAuthor: 'J.R.R. Tolkien was an English writer, poet, and philologist, best known for The Hobbit and The Lord of the Rings.' },

  // Category 8 (new 4 books added)
  { id: 21, categoryId: 8, title: 'The Great Gatsby', author: 'F. Scott Fitzgerald', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/TheGreatGatsby_1925jacket.jpeg/330px-TheGreatGatsby_1925jacket.jpeg', description: 'A novel about the American dream and the roaring twenties.', price: 13.5, productDetail: 'Paperback, 180 pages, Publisher: Scribner, Language: English', aboutAuthor: 'F. Scott Fitzgerald was an American novelist and short story writer.' },
  { id: 22, categoryId: 8, title: 'Moby Dick', author: 'Herman Melville', image: 'https://upload.wikimedia.org/wikipedia/commons/4/41/Moby-Dick_FE_title_page.jpg', description: 'The adventures of Captain Ahab and the white whale.', price: 15, productDetail: 'Hardcover, 585 pages, Publisher: Harper & Brothers, Language: English', aboutAuthor: 'Herman Melville was an American novelist, short story writer, and poet.' },
  { id: 23, categoryId: 8, title: 'Pride and Prejudice', author: 'Jane Austen', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/PrideAndPrejudiceTitlePage.jpg/330px-PrideAndPrejudiceTitlePage.jpg', description: 'A classic romance novel set in 19th century England.', price: 12.5, productDetail: 'Paperback, 279 pages, Publisher: T. Egerton, Language: English', aboutAuthor: 'Jane Austen was an English novelist known for her social commentary and romantic fiction.' }
];
